language: cpp

compiler:
  - gcc
  - clang

sudo: false

git:
  depth: 1

env:
  global:
    - LLVM_VERSION=3.7.0
    - LLVM_ARCHIVE_PATH=$HOME/clang+llvm.tar.xz

before_install:
  - wget http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $LLVM_ARCHIVE_PATH
  - mkdir $HOME/clang+llvm
  - tar xf $LLVM_ARCHIVE_PATH -C $HOME/clang+llvm --strip-components 1
  - export PATH=$HOME/clang+llvm/bin:$PATH
  - ln -s $HOME/clang+llvm/bin/clang++ $HOME/clang+llvm/bin/clang++-3.7

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5
      - libhiredis-dev

install:
  # install some packages from Ubuntu's default sources
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

script:
  # make distcheck still does not work on travis
  - mkdir build
    && cd build
    && cmake ..
       -DCMAKE_C_FLAGS="-Werror"
       -DCMAKE_CXX_FLAGS="-Werror"
    && make VERBOSE=1
    && (make test || true)

after_script:
  - if test -f ./Testing/Temporary/LastTest.log; then
      echo "cat test logs:";
      cat  ./Testing/Temporary/LastTest.log;
    fi
